root = "."
tmp_dir = ".tmp"

[build]
  bin = """.\
    tmp/netdata-digest \
    ${HOST+-host "$HOST"} \
    ${PORT+-port "$PORT"} \
    ${REDIS_ADDR+-redis-addr "$REDIS_ADDR"} \
    ${NATS_URL+-nats-url "$NATS_URL"} \
    """
  cmd = "go build -o .tmp/netdata-digest ./cmd/netdata-digest"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true
