version: "3.7"

services:
  server:
    image: golang:1.16.5-stretch
    working_dir: /go/src/server
    command: make serve
    restart: unless-stopped
    environment:
      - PORT=3000
      - NATS_URL=nats://nats:4222
    ports:
      - 3000:3000
    volumes:
      - .:/go/src/server

  redis:
    image: redis:6.2.4-alpine
    command: --appendonly yes
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - netdatadigest_redis:/data

  nats:
    image: docker.io/lvrach/be-challenge:latest
    restart: unless-stopped
    ports:
      - 4222:4222

volumes:
  netdatadigest_redis:
